# Generated by Django 4.2.23 on 2025-06-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('usertype', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(help_text='Enter the question text here.', max_length=255)),
                ('category', models.CharField(help_text='This is the correct answer / category.', max_length=100)),
                ('option1', models.CharField(help_text='Wrong option 1', max_length=100)),
                ('option2', models.CharField(help_text='Wrong option 2', max_length=100)),
                ('option3', models.CharField(help_text='Wrong option 3', max_length=100)),
                ('image', models.FileField(help_text='Upload image for the question.', upload_to='question_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('cancer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cancer_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to='user_profiles/')),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionapp.login')),
            ],
        ),
    ]
