# Generated by Django 4.2.23 on 2025-06-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Question',
        ),
    ]
