# Generated by Django 4.2.23 on 2025-07-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0002_postquestion_postresult_spontaniousquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spontaniousquestion',
            name='Main_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spontaniousquestion',
            name='Sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
