# Generated by Django 4.2.23 on 2025-08-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0003_spontaniousquestion_main_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload image for the question.', upload_to='Demo_question_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
