# Generated by Django 4.2.23 on 2025-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0004_remove_result_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(help_text='Upload image for the question.', upload_to='question_images/'),
        ),
    ]
