# Generated by Django 4.2.23 on 2025-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0004_demoquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoquestion',
            name='category',
            field=models.CharField(default=1, help_text='This is the correct answer / category.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demoquestion',
            name='option1',
            field=models.CharField(blank=True, help_text='Wrong option 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoquestion',
            name='option2',
            field=models.CharField(blank=True, help_text='Wrong option 2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoquestion',
            name='option3',
            field=models.CharField(blank=True, help_text='Wrong option 3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoquestion',
            name='option4',
            field=models.CharField(blank=True, help_text='Wrong option 3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoquestion',
            name='option5',
            field=models.CharField(blank=True, help_text='Wrong option 3', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoquestion',
            name='option6',
            field=models.CharField(blank=True, default='Neutral', help_text='Wrong option 4', max_length=100, null=True),
        ),
    ]
