# Generated by Django 4.2.23 on 2025-08-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionapp', '0005_demoquestion_category_demoquestion_option1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('QUESTIONID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionapp.demoquestion')),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionapp.user_model')),
            ],
        ),
    ]
